// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';

export const environment = {
  production: true,
  version: '(prod)',
  serverUrl: 'http://localhost:59738', //dok dodjemo do toga, ovo ce trebati promjeniti na pravi produkcijski url
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
